create table
  public.users (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    username text not null,
    email text not null,
    password text null,
    full_name text null,
    auth_token uuid not null default gen_random_uuid (),
    wallet double precision not null default '0'::double precision,
    constraint users_pkey primary key (id),
    constraint users_auth_token_key unique (auth_token),
    constraint users_email_key unique (email),
    constraint users_id_key unique (id),
    constraint users_username_key unique (username)
  ) tablespace pg_default;

create table
  public.catalog (
    id bigint generated by default as identity,
    title text null,
    brand text null,
    size text null,
    price numeric null,
    created_at timestamp with time zone not null default now(),
    user_id bigint not null,
    quantity bigint not null default '0'::bigint,
    constraint catalog_pkey primary key (id),
    constraint catalog_id_key unique (id),
    constraint catalog_user_id_fkey foreign key (user_id) references users (id)
  ) tablespace pg_default;

create table
  public.catalog_ledger (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    customer_id bigint not null,
    catalog_id bigint not null,
    quantity integer not null default 0,
    constraint catalog_ledger_pkey primary key (id),
    constraint catalog_ledger_id_key unique (id),
    constraint catalog_ledger_catalog_id_fkey foreign key (catalog_id) references catalog (id),
    constraint catalog_ledger_customer_id_fkey foreign key (customer_id) references users (id)
  ) tablespace pg_default;

create table
  public.carts (
    cart_id bigint generated by default as identity,
    bought boolean null default false,
    created_at timestamp with time zone not null default now(),
    catalog_id bigint null,
    user_id bigint not null,
    constraint carts_pkey primary key (cart_id),
    constraint carts_cart_id_key unique (cart_id),
    constraint carts_catalog_id_fkey foreign key (catalog_id) references catalog (id),
    constraint carts_user_id_fkey foreign key (user_id) references users (id)
  ) tablespace pg_default;

create table
  public.cart_items (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    cart_id bigint null,
    catalog_id bigint null,
    quantity bigint null,
    constraint cart_items_pkey primary key (id),
    constraint cart_items_id_key unique (id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (cart_id),
    constraint cart_items_catalog_id_fkey foreign key (catalog_id) references catalog (id)
  ) tablespace pg_default;