create table
  public.users (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    username text null,
    email text null,
    password text null,
    full_name text null,
    constraint users_pkey primary key (id)
  ) tablespace pg_default;