create table
  public.users (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    username text null,
    email text null,
    password text null,
    full_name text null,
    auth_token uuid null default gen_random_uuid (),
    wallet double precision not null default '0'::double precision,
    constraint users_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.catalog (
    id bigint generated by default as identity,
    title text null,
    brand text null,
    size smallint null,
    price numeric null,
    created_at timestamp with time zone not null default now(),
    user_id bigint not null,
    quantity bigint not null default '1'::bigint,
    constraint catalog_pkey primary key (id),
    constraint catalog_user_id_fkey foreign key (user_id) references users (id)
  ) tablespace pg_default;

create table
  public.carts (
    cart_id bigint generated by default as identity,
    bought boolean null,
    created_at timestamp with time zone not null default now(),
    catalog_id bigint null,
    user_id bigint not null,
    constraint carts_pkey primary key (cart_id),
    constraint carts_catalog_id_fkey foreign key (catalog_id) references catalog (id),
    constraint carts_user_id_fkey foreign key (user_id) references users (id)
  ) tablespace pg_default;
